// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orcusrkjjpdxtxkjefki.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yY3VzcmtqanBkeHR4a2plZmtpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NTc2ODEsImV4cCI6MjA3MTMzMzY4MX0.0IyPMlNCaTw78PwlQX3yMUGe0fp86HAfiSEJxTpWEpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});